/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package volare.vista;

/**
 *
 * @author Francisco
 */
public class Buscar extends javax.swing.JPanel {

    /**
     * Creates new form Search
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldCorreoElectronico = new javax.swing.JTextField();
        textFieldConstrasenia = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        textFieldConstrasenia1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 89, 182));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(700, 600));

        textFieldCorreoElectronico.setBackground(new java.awt.Color(155, 89, 182));
        textFieldCorreoElectronico.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        textFieldCorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        textFieldCorreoElectronico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCorreoElectronico.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));

        textFieldConstrasenia.setBackground(new java.awt.Color(155, 89, 182));
        textFieldConstrasenia.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        textFieldConstrasenia.setForeground(new java.awt.Color(255, 255, 255));
        textFieldConstrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldConstrasenia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));
        textFieldConstrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConstraseniaActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(99, 64, 113));
        searchButton.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Buscar");
        searchButton.setBorder(null);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        textFieldConstrasenia1.setBackground(new java.awt.Color(155, 89, 182));
        textFieldConstrasenia1.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        textFieldConstrasenia1.setForeground(new java.awt.Color(255, 255, 255));
        textFieldConstrasenia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldConstrasenia1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 255, 255)));
        textFieldConstrasenia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConstrasenia1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha:");

        jLabel2.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Origen:");

        jLabel3.setFont(new java.awt.Font("Nunito", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Destino:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldConstrasenia)
                    .addComponent(textFieldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldConstrasenia1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldConstrasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldConstrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(498, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldConstraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConstraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldConstraseniaActionPerformed

    private void textFieldConstrasenia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConstrasenia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldConstrasenia1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField textFieldConstrasenia;
    private javax.swing.JTextField textFieldConstrasenia1;
    private javax.swing.JTextField textFieldCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
