/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package volare.vista;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import volare.modelo.Asiento;
import volare.modelo.AsientoData;
import volare.modelo.Ciudad;
import volare.modelo.CiudadData;
import volare.modelo.CompraData;
import volare.modelo.Conexion;
import volare.modelo.PasajeroData;
import volare.modelo.Vuelo;
import volare.modelo.VueloData;

/**
 *
 * @author Usuario
 */
public class Vuelos extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private CompraData compraData;
    private ArrayList<Ciudad> listaCiudad;
    private ArrayList<Vuelo> listaVuelos;
    private CiudadData ciudadData;
    private VueloData vueloData;
    private PasajeroData pasajeroData;
    private Conexion conexion;
    private AsientoData asientoData;
    private ArrayList<Asiento> listaAsientos;
    
    /** Creates new form Vuelos */
    public Vuelos() {
        initComponents();
        
        try {
            
            conexion = new Conexion("jdbc:mysql://localhost/volare", "root", "");
            modelo = new DefaultTableModel();
            ciudadData = new CiudadData(conexion);
            listaCiudad = ciudadData.obtenerCiudades();
            vueloData = new VueloData(conexion);
            pasajeroData = new PasajeroData(conexion);
            asientoData = new AsientoData(conexion);
            compraData = new CompraData(conexion);
            cargarCiudades();
            armarCabeceraTabla();
        } catch (ClassNotFoundException ex) {
            System.out.println("Error: "+ex.getMessage());
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVuelos = new javax.swing.JTable();
        cbDestino = new javax.swing.JComboBox<>();
        cbOrigen = new javax.swing.JComboBox<>();
        jButtonComprarVuelo = new javax.swing.JButton();
        jTextFieldDni = new javax.swing.JTextField();
        jPasswordCompraVuelo = new javax.swing.JPasswordField();
        jLabelSeleccionDeVuelos = new javax.swing.JLabel();
        jButtonBuscarVuelos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelVueloSeleccionado = new javax.swing.JLabel();
        jlLogoBuscar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbAsientos = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(null);

        jTableVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVuelos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableVuelosFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVuelos);

        cbDestino.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N

        cbOrigen.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N

        jButtonComprarVuelo.setBackground(new java.awt.Color(51, 204, 0));
        jButtonComprarVuelo.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N
        jButtonComprarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComprarVuelo.setText("Comprar!");
        jButtonComprarVuelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonComprarVuelo.setContentAreaFilled(false);
        jButtonComprarVuelo.setOpaque(true);
        jButtonComprarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarVueloActionPerformed(evt);
            }
        });

        jLabelSeleccionDeVuelos.setFont(new java.awt.Font("Myriad Pro Light", 1, 18)); // NOI18N
        jLabelSeleccionDeVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeleccionDeVuelos.setText("Busca tus vuelos por ciudad de origen y destino (fecha opcional)");

        jButtonBuscarVuelos.setBackground(new java.awt.Color(51, 204, 0));
        jButtonBuscarVuelos.setFont(new java.awt.Font("Miriam", 1, 14)); // NOI18N
        jButtonBuscarVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarVuelos.setText("Buscar");
        jButtonBuscarVuelos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBuscarVuelos.setContentAreaFilled(false);
        jButtonBuscarVuelos.setOpaque(true);
        jButtonBuscarVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarVuelosMouseClicked(evt);
            }
        });
        jButtonBuscarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarVuelosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DNI");

        jLabel2.setFont(new java.awt.Font("Miriam", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        jLabelOrigen.setFont(new java.awt.Font("Miriam", 0, 14)); // NOI18N
        jLabelOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrigen.setText("Origen");

        jLabelDestino.setFont(new java.awt.Font("Miriam", 0, 14)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestino.setText("Destino");

        jLabel3.setFont(new java.awt.Font("Miriam", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Salida");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volare/vista/img/buttons/compras.png"))); // NOI18N

        jLabelVueloSeleccionado.setFont(new java.awt.Font("Myriad Pro Light", 0, 18)); // NOI18N
        jLabelVueloSeleccionado.setForeground(new java.awt.Color(255, 255, 255));

        jlLogoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volare/vista/img/buttons/buscar.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Myriad Pro Light", 0, 29)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volare/vista/img/91605-200.png"))); // NOI18N
        jLabel4.setText("asientos");

        jLabel5.setFont(new java.awt.Font("Myriad Pro Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Disponibles :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogoBuscar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOrigen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonBuscarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSeleccionDeVuelos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelVueloSeleccionado))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPasswordCompraVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonComprarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSeleccionDeVuelos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabelDestino)
                        .addComponent(jButtonBuscarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonComprarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelLogo)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordCompraVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabelVueloSeleccionado))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarVuelosActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButtonBuscarVuelosActionPerformed

    private void jButtonBuscarVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarVuelosMouseClicked
        // TODO add your handling code here:
        cargarDatos();
        
    }//GEN-LAST:event_jButtonBuscarVuelosMouseClicked

    private void jTableVuelosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableVuelosFocusGained
        // TODO add your handling code here:
        listarAsientosVuelo();
        cargarAsientos();
    }//GEN-LAST:event_jTableVuelosFocusGained

    private void jButtonComprarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarVueloActionPerformed
        // TODO add your handling code here:
        
        Asiento asiento =(Asiento)cbAsientos.getSelectedItem();
        String dni = jTextFieldDni.getText();
        
        String password=pasajeroData.obtenerPassPasajero(Integer.parseInt(dni));
        String passwordCom= jPasswordCompraVuelo.getText();
        if(passwordCom.equals(password)){
            compraData.comprarAsiento(asiento);
            compraData.generarCompra((int)jTableVuelos.getValueAt(jTableVuelos.getSelectedRow(), 0), Integer.parseInt(dni), asiento.getId());
            this.removeAll();
            this.repaint();
            this.moveToFront();
            JOptionPane.showMessageDialog(this, "La compra se ha realizado con exito!");
        }else JOptionPane.showMessageDialog(this, "DNI y/o password incorrecto tipeo");
        
        
        
    }//GEN-LAST:event_jButtonComprarVueloActionPerformed

    
    public void listarAsientosVuelo(){
        
        int contAsientos=0;
        
        int idVuelo=(int)jTableVuelos.getValueAt(jTableVuelos.getSelectedRow(), 0);
        
        Vuelo vuelo = vueloData.consultarVuelo(idVuelo);
        
        List <Asiento> asientos =asientoData.obtenerAsientosDisponiblesAvion(vuelo.getAvion());
        
        contAsientos = asientos.size();
        
        jLabelVueloSeleccionado.setText(String.valueOf(contAsientos)); 
        
      }
    
    public void cargarAsientos(){
        
        int idVuelo= (int)jTableVuelos.getValueAt(jTableVuelos.getSelectedRow(), 0);
        
        Vuelo vuelo = vueloData.consultarVuelo(idVuelo);
        
        listaAsientos=(ArrayList)asientoData.obtenerAsientosDisponiblesAvion(vuelo.getAvion());
        
        for(Asiento item:listaAsientos){
            cbAsientos.addItem(item);
           }
        
    }
    
    public void cargarCiudades(){
        
        for(Ciudad item:listaCiudad){
            
            cbOrigen.addItem(item);
            cbDestino.addItem(item);
            
        }
        
    }
    
    public void armarCabeceraTabla(){
        
        ArrayList<Object> columns = new ArrayList<Object>();
        columns.add("ID Vuelo");
        columns.add("Precio");
        columns.add("Fecha de Salida");
        columns.add("Fecha de llegada");
        columns.add("Refuerzo");
        /*columns.add("ID aeropuerto salida");
        columns.add("Codigo aeropuerto");
        columns.add("ID ciudad salida");
        columns.add("Nombre");
        columns.add("ID Pais salida");
        columns.add("Nombre");
        columns.add("Provincia salida");
        columns.add("ID aeropuerto llegada");
        columns.add("Codigo aeropuerto");
        columns.add("ID ciudad llegada");
        columns.add("Nombre");
        columns.add("ID Pais llegada");
        columns.add("Nombre");
        columns.add("Provincia llegada");
        columns.add("Estado del vuelo");*/
        
        for(Object it:columns){
            
            modelo.addColumn(it);
            
        }
        jTableVuelos.setModel(modelo);
    }
    
    public void borrarFilas(){
        int a = modelo.getRowCount()-1;
        
        for(int i=a;i>=0;i--){
            
            modelo.removeRow(i);
        }
        
        
    }
    
    public void cargarDatos(){
        borrarFilas();
        
        Ciudad ciudad =(Ciudad)cbOrigen.getSelectedItem();
        
        Ciudad ciudadDes =(Ciudad)cbDestino.getSelectedItem();
        
        listaVuelos =(ArrayList)vueloData.consultarVuelos(ciudad,ciudadDes);
        
        for(Vuelo v:listaVuelos){
            
            modelo.addRow(new Object []{v.getId(),v.getPrecio(),v.getFechaSalida(),v.getFechaLlegada(),v.isRefuerzo()});
            
        }
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Asiento> cbAsientos;
    private javax.swing.JComboBox<Ciudad> cbDestino;
    private javax.swing.JComboBox<Ciudad> cbOrigen;
    private javax.swing.JButton jButtonBuscarVuelos;
    private javax.swing.JButton jButtonComprarVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelSeleccionDeVuelos;
    private javax.swing.JLabel jLabelVueloSeleccionado;
    private javax.swing.JPasswordField jPasswordCompraVuelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVuelos;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JLabel jlLogoBuscar;
    // End of variables declaration//GEN-END:variables

}
